version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MONGO_URL=mongodb://mongo:27017
      - JWT_SECRET=your-super-secret-key-change-in-production
      - DEBUG=false
    depends_on:
      - mongo
    volumes:
      - uploads:/tmp/uploads

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: estimation_db

volumes:
  mongo_data:
  uploads:
